timeout: 60000
baseURL: 'https://hi-ernest.github.io/'
title: Always Exploring
theme: hugo-theme-ladder
license: MIT
licenselink: 'https://github.com/guangzhengli/hugo-theme-ladder/blob/master/LICENSE'
description: ''
homepage: 'https://hi-ernest.github.io/'
defaultContentLanguage: 'zh'
paginate: 10
hasCJKLanguage: true
copyright: "2023 ErnestChen All rights reserved"
Author:
  name: "Ernest Chen"
  email: "ernestchen247@gmail.com"
menu:
  main:
    - name: Blog
      url: /blog
      weight: 1
    - name: Archive
      url: /archives
      weight: 2
    - name: Guest
      url: /guestbook
      weight: 3
    - name: Monitor
      url: https://umami-blog-analyze-30k29jpw4-hi-ernest.vercel.app/share/F0HNiV8DX3mdMGa3/hi-Ernest
      weight: 4
params:
  brand: HOME
  avatarURL: /images/avatar.png
  author: hi-Ernest
  authorDescription:
  info:
  favicon: /images/avatar.png
  options:
    showDarkMode: true
    enableImgZooming: true
    enableMultiLang: true
    showMetaTags: true
  darkModeTheme: data-dark-mode
  sponsors:
    title: Sponsors
    description: Support me by becoming a sponsor
    buymeaCoffee:
      enable: true
      url: https://www.buymeacoffee.com/iguangzhengli
      button_api: https://img.buymeacoffee.com/button-api/?text=Buy me a coffee&emoji=&slug=iguangzhengli&button_colour=FFDD00&font_colour=000000&font_family=Cookie&outline_colour=000000&coffee_colour=ffffff
      qr: https://storage.guangzhengli.com/images/buymeacoffee_sponsors.png
    wechat:
      enable: true
      qr: https://storage.guangzhengli.com/images/alipay_sponsors.jpeg
    alipay:
      enable: true
      qr: https://storage.guangzhengli.com/images/weixin_sponsors.jpeg
  comments:
    giscus:
      enable: true
      repo: hi-Ernest/blog-comments
      repo_id: R_kgDOKfq-Xw
      category: Announcements
      category_id: DIC_kwDOKfq-X84CaFwF
      mapping: pathname
      position: top
      lang: zh-CN # pick a language from https://github.com/giscus/giscus/tree/main/locales
    utteranc:
      enable: false 
      repo:
      issueTerm:
  analytics:
    google:
      SiteVerificationTag: xxx 
    umami:
      enable: true 
      website_id: f3deb06c-5a53-49a7-a8e1-b4ce23c412ba 
      url: https://umami-blog-analyze-30k29jpw4-hi-ernest.vercel.app/hugo-ladder 
  guestbook:
    title: Guestbook 
    description: Leave a comment below. It could be anything –- question, appreciation, information, or even humor.
  # social:
  #   - name: Resume 
  #     pre: >-
  #       <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-github"><path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77A5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42,3.3,6.61,6.44,7A3.37,3.37,0,0,0,9,18.13V22"></path></svg>
  #     url:'https://github.com/hi-Ernest/resume/blob/master/resume-zh.pdf'
languages:
  # en:
  #   languageName: EN 
  zh:
    languageName: 中 
    params:
      authorDescription: 专注当下，感恩当下 
      info: 不断探索！日拱一卒！ 
      guestbook:
        title: 留言板 
        description: 留下痕迹 
      menu:
        main:
          - name: 文章
            url: /blog
            weight: 1
          - name: 历史
            url: /archives
            weight: 2
          - name: 留言板
            url: /guestbook
            weight: 3
          - name: 统计 
            url: https://umami-blog-analyze-30k29jpw4-hi-ernest.vercel.app/share/F0HNiV8DX3mdMGa3/hi-Ernest 
            weight: 4
taxonomies:
  series: series
  tag: tags